### ISSUE TITLE
Console reports unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by wangchunyu78** [foreverddong/TXCrawl#2]
[NOTICE]  4/11/2020 7:46:53 AM  Starting TXCrawl WinForms GUI....
[NOTICE]  4/11/2020 7:46:53 AM  This is a very early test version, visit https://github.com/foreverddong/TXCrawl to submit issues.
[NOTICE]  4/11/2020 7:47:01 AM  Successfully loaded 3 items into your current queries
[NOTICE]  4/11/2020 7:47:05 AM  Started Executing 3 queries...
[NOTICE]  4/11/2020 7:47:05 AM  Running query for 4/19/2020 ICN->PVG...
[ERROR]  4/11/2020 7:47:11 AM  Encountered Error when executing query 4/19/2020 ICN->PVG
[ERROR]  4/11/2020 7:47:11 AM  Exception Info: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Users\wcy\AppData\Local\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[NOTICE]  4/11/2020 7:47:11 AM  Running query for 4/21/2020 ICN->CGQ...
[ERROR]  4/11/2020 7:47:15 AM  Encountered Error when executing query 4/21/2020 ICN->CGQ

**Comment by feliscafra** [comment]
I noticed that your chrome installation folder is unusual (%APPDATA% as opposed to %PROGRAMFILES%) which might indicate that you are running an older version of Chrome. Currently, the WebDriver package supports Chrome 79 (v0.9-alpha) and Chrome 81(v0.91-alpha). Check and update your chrome version in Settings -> About Chrome or do a fresh reinstallation.
